version: '3'

services:
  ugc:
    build: ./ugc-api
    container_name: ugc
    entrypoint: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port $UGC_PORT"
    expose:
      - ${UGC_PORT}
    env_file:
      - ./.env

  etl_ugc:
    build: ./etl_ugc
    container_name: etl_ugc
    entrypoint: >
      sh -c "python etl.py"
    env_file:
      - ./.env

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - ugc
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/site.conf:/etc/nginx/conf.d/site.conf:ro
    ports:
      - "80:80"
      - "8000:80"

networks:
  default:
    name: movies_networks
    external: true